### ISSUE TITLE
User can view a timer for each question 

### ISSUE THREAD

**Issue by ajswanwick** [MFS4711/collaboration-practice#10]
As a User i want to have a countdown timer for each question soi can feel the pressure of time while answering

## Acceptance Criteria
* The timer counts down from a set time
* If the timer runs out, the answer is marked as incorrect
* the incorrect answer is added to the incorrect answers total

## Tasks
- [ ] implement a function that operates a a countdown timer
- [ ] the function needs to mark answer "incorrect " if timer reaches zero
- [ ] add visualisation to the timer as a countdown
