### ISSUE TITLE
user can see a streak counter for consecutive correct answers

### ISSUE THREAD

**Issue by ajswanwick** [MFS4711/collaboration-practice#24]
As a user, I want to know how many correct answers I’ve gotten in a row to challenge myself to keep the streak going.

## Acceptance Criteria
* The game displays a counter which adds one for each correct answer
* The streak counter resets to zero when with an incorrect answer
* etc.

## Tasks
- [ ] Create visual display for the counter
- [ ] create a function that adds 1 when correct answer submitted
- [ ] counter resets to zero when incorrect answer is submitted
