### ISSUE TITLE
User can see leaderboards to compare scores with others

### ISSUE THREAD

**Issue by ajswanwick** [MFS4711/collaboration-practice#26]
As a user, I want to see a leaderboard that shows the highest scores so I can compete with others

## Acceptance Criteria
* create a table that logs users and their scores
* table displays scores in order from best to worst 
* etc.

## Tasks
- [ ] create a leaderboard for the user
- [ ] create a function that logs a users score and compares it to the other scores
- [ ] create a function that ranks scores from highest to lowest
