### ISSUE TITLE
User can restart game after completing it 

### ISSUE THREAD

**Issue by ajswanwick** [MFS4711/collaboration-practice#27]
As a user, I want to have the option to play again right after finishing a game without having to navigate back to the main menu.

## Acceptance Criteria
* User can click a button at the end of the game to restart quiz
* the button should re-start quiz and not navigate to main menu 
* 

## Tasks
- [ ] create re-start quiz button
- [ ] create function that restarts the quiz
- [ ] the user is returned to the correct page
